kind: Service
apiVersion: v1
metadata:
  name: blog-{{.Chart.Version}}
  namespace: {{.Values.namepsace}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    io.godwit.service:  blog-{{.Chart.Version}}
  type: ClusterIP
---